### ISSUE TITLE
examples/easy_start/spm_auditory_preproc.ini : Syntax Error

### ISSUE THREAD

**Issue by mmayolini** [neurospin/pypreprocess#200]
Hi everyone,

When I try to execute the command from "Getting started" part of README ("cd examples/easy_start", then "python spm_auditory_preproc.ini"), I get the following error : 

File "spm_auditory_preproc.ini", line 57
    subject_dirs = sub*

Do you have any solution to solve the problem ?

**Comment by dohmatob** [comment]
Hi there,

Thanks for reporting this. Ah, that was a mis-print. We intended to type

`python nipype_preproc_spm_auditory.py`

I've corrected the Readme file. Please could you confirm that the problem goes away. Thanks.

**Comment by mmayolini** [comment]
I get a "RunTimeError : Failed to configure SPM!", but I think it's a problem about my configuration, so the initial problem is corrected I guess.

**Comment by dohmatob** [comment]
There are two cases:
* If you have matlab and spm installed, then specify the location of your spm installation directory like so
 
`export SPM_DIR=/path/to/spm/installation/dir`

* if you've installed a pre-compiled version of SPM (see Readme file) then, specify the location of the spm executable like so

`export SPM_MCR=/path/to/spm_mcr_script`

These variables are consumed by the `pypreprocess/configure_spm.py` module to configure your spm / matlab for use in pypreprocess.

**Comment by mmayolini** [comment]
Well, I'm in the first case you mentioned and I currently have the following line in my .bashrc file : 
"export SPM_PATH=/usr/local/spm12/"

So I suppose I had to run "export SPM_DIR=/usr/local/spm12/" in my terminal, then try again "python nipype_preproc_spm_auditory.py" in "examples/easy_start", but the bug remains, so I may have done something wrong...

**Comment by mmayolini** [comment]
Here is the full traceback : 

/home/neuro/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/configure_spm.py:143: UserWarning: Failed to configure SPM!
  warnings.warn('Failed to configure SPM!')
Using the following parameters for preprocessing:
	normalize=False
	coreg_anat_to_func=False
	slice_timing_software=spm
	output_modulated_tpms=True
	func_write_voxel_sizes=[3.0, 3.0, 3.0]
	anat_write_voxel_sizes=[1.0, 1.0, 1.0]
	dataset_description=<a href=http://www.fil.ion.ucl.ac.uk/spm/data/auditory/>SPM Auditory
 (single-subject)</a>

	smooth_software=spm
	realign_software=spm
	register_to_mean=True
	deleteorient=False
	dataset_dir=/home/neuro/nilearn_data/spm_auditory
	report=True
	dataset_id=/home/neuro/nilearn_data/spm_auditory
	realign_reslice=False
	segment=True
	interleaved=False
	coregister_software=spm
	anat_fwhm=0.0
	spm_dir=None
	dartel=False
	coregister_reslice=False
	fwhm=[5.0, 5.0, 5.0]
	newsegment=True
	TR=7.0
	realign=True
	coregister=True
	slice_order=ascending
	slice_timing=True
	caching=True
	tsdiffana=True
	matlab_exec=/usr/local/MATLAB/R2012b/bin/matlab
	TA=TR * (1 - 1 / nslices)
/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py:1564: UserWarning: There is only one subject. Disabling NewSegment.
  warnings.warn("There is only one subject. Disabling NewSegment.")
[Memory]    0.0s, 0.0min: Loading niigz2nii from /home/neuro/nilearn_data/spm_auditory/pypreprocess_output/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/4b0809575d1210fcdfa2b71165a78dc6
___________________________________________niigz2nii cache loaded - 0.0s, 0.0min
[Memory]    0.0s, 0.0min: Loading niigz2nii from /home/neuro/nilearn_data/spm_auditory/pypreprocess_output/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/ebfa04785ab449a11306409ad63c68bc
___________________________________________niigz2nii cache loaded - 0.0s, 0.0min
Traceback (most recent call last):
  File "nipype_preproc_spm_auditory.py", line 49, in <module>
    subject_data = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)[0]
  File "/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1701, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/neuro/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1279, in do_subject_preproc
    hardlink_output=hardlink_output
  File "/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 167, in _do_subject_slice_timing
    spm_mcr=spm_mcr)
  File "/home/neuro/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 104, in _configure_backends
    raise RuntimeError("Failed to configure SPM!")
RuntimeError: Failed to configure SPM!

**Comment by dohmatob** [comment]
@mmayolini:  I'll make time and get back to this. I think we could make the configuration of the SPM and matlab more robust and user-friendly process. In principle, we can evade such errors backend.

**Comment by mmayolini** [comment]
@dohmatob : thanks for the reply ! No problem, I'll wait the time you need.

**Comment by KamalakerDadi** [comment]
I am on this.

**Comment by dohmatob** [comment]
OK, thanks.

**Comment by KamalakerDadi** [comment]
I felt this is a documentation issue. So, a fix in #208

**Comment by bthirion** [comment]
@mmayolini , can we close the issue ?
